name: Build
on:
  push:
    branches: [main]
jobs:
  dispatch:
    runs-on: self-hosted
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DISPATCH_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'outsideworx',
              repo: 'sites',
              event_type: 'build-tunde-divat',
              client_payload: { name: 'tunde-divat' }
            })
